import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/lib/provider";
import MainLayout from "./_layouts/mainLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor:"#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={` banana`}>
        <Providers>
          <MainLayout>
          {children}
          </MainLayout>
        </Providers>
      </body>
    </html>
  );
}
